[package]
name = "nexus-prover"
edition.workspace = true
version.workspace = true
publish = false

[dependencies]
clap.workspace = true

#rayon = "1.8"

zstd = { version = "0.12", default-features = false }

nexus-riscv = { path = "../riscv" }
nexus-riscv-circuit = { path = "../riscv-circuit" }

supernova.workspace = true

ark-serialize.workspace = true
ark-crypto-primitives.workspace = true
ark-ec.workspace = true
ark-ff.workspace = true
ark-relations.workspace = true
ark-r1cs-std.workspace = true

ark-pallas.workspace = true
ark-vesta.workspace = true

[features]
default = [ "parallel" ]
parallel = [
   "ark-ff/parallel",
   "ark-ec/parallel",
   #"ark-std/parallel",
   "ark-crypto-primitives/parallel",
   "ark-r1cs-std/parallel",
   "supernova/parallel",
]
ns = []

[[bench]]
name = "genpp"
harness = false

[[bench]]
name = "cubic"
harness = false
