[package]
name = "nexus-tools-dev"
edition.workspace = true
version.workspace = true
authors.workspace = true
homepage.workspace = true
repository.workspace = true
keywords.workspace = true
categories.workspace = true
publish.workspace = true
default-run = "cargo-nexus"

[[bin]]
name = "cargo-nexus"
path = "src/bin/cargo-nexus.rs"

[[bin]]
name = "nexus-run"
path = "src/bin/nexus-run.rs"
required-features = ["dev"]

[dependencies]
clap.workspace = true

nexus-config = { path = "../../config", features = ["clap_derive"], optional = true }

anyhow = "1.0"
cargo_metadata = "0.18.1"
tracing = { version = "0.1", default-features = false, features = ["std"] }
tracing-subscriber = { version = "0.3", default-features = false, features = [
   "fmt",
   "ansi",
   "chrono",
] }
toml = { version = "0.8.8", optional = true }

[features]
default = ["dev"]
dev = ["nexus-config", "toml"]
