[package]
name = "nexus-tools"
authors = { workspace = true }
version = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
repository = { workspace = true }
publish = { workspace = true }
keywords = { workspace = true }
categories = { workspace = true }

[[bin]]
name = "cargo-nexus"
path = "src/cargo-nexus.rs"

[[bin]]
name = "nexus-run"
path = "src/nexus-run.rs"

[dependencies]
cargo_metadata = "0.18.1"
clap.workspace = true
serde_json.workspace = true
nexus-riscv = { path = "../riscv" }
nexus-prover = { path = "../prover" }
nexus-network = { path = "../network" }
supernova = { path = "../supernova" , features = ["spartan"]}
ark-spartan = { path = "../spartan" }
ark-serialize.workspace = true
